sudo: require
services:
  - docker

before_install:
  - docker build -t weitingc219/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true weitingc219/docker-react-practice npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker-react-practice'
  env: 'DockerReactPractice-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-557655015345'
  bucket_path: 'docker-react-practice'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
