sudo: require
services:
  - docker

before_install:
  - docker build -t weitingc219/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true weitingc219/docker-react-practice npm run test
